name: app_desafio
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  path_provider: ^2.1.5
  sqlite3: ^2.7.5
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.3.0
  geocoding: ^3.0.0
  image_picker: ^1.1.2
  shared_preferences: ^2.5.3
  freezed_annotation: ^3.0.0

  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  freezed: ^3.0.6
  bloc_test: ^10.0.0
  bloc_lint: ^0.2.0-dev.3

flutter:

  uses-material-design: true
  assets:
    - assets/images/localizacao/
    - assets/images/logo/
    - assets/buttons/
  fonts:
    - family: LobsterTwo
      fonts:
        - asset: assets/fonts/LobsterTwo-Regular.ttf
        - asset: assets/fonts/LobsterTwo-Bold.ttf
          weight: 700
        - asset: assets/fonts/LobsterTwo-Italic.ttf
          style: italic
        - asset: assets/fonts/LobsterTwo-BoldItalic.ttf
          weight: 700
          style: italic
